Repository GoMyamMii/Culture.map-, pull requests merged in 2023-01, with the labels that each got.

#10 fix : fixed not used map function
  src/pages/Detail.jsx
Labels: fix

#17 fix : image exception handling
  public/image/no-image.png
  src/components/ListItem.tsx
  src/pages/Detail.tsx
Labels: fix

#18 refctor : add search button to main,add SkeletonUI
  src/api.tsx
  src/components/ListItem.tsx
  src/pages/Main.tsx
Labels: fix

#25 fix : fix images
  public/image/mainVisual/mainVisual01.jpg
  public/image/mainVisual/mainVisual02.jpg
  public/image/mainVisual/mainVisual03.jpg
  src/components/CarouselImg.tsx
  src/components/MainCarousel.tsx
  src/pages/Detail.tsx
Labels: fix

#27 Apply page nation
  src/api.tsx
  src/components/Header.tsx
  src/components/ListItem.tsx
  src/components/Modal.tsx
  src/components/ReviewList.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
Labels: enhancement

#32 fix css select button in Main
  package.json
  src/App.tsx
  src/api.tsx
  src/components/ListItem.tsx
  src/components/MainCarousel.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  yarn.lock
Labels: enhancement, fix

#40 fix main page Carousel
  src/components/CarouselImg.tsx
  src/components/MainCarousel.tsx
Labels: fix

#41 refactor ui
  src/api.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ListItem.tsx
  src/components/MainCarousel.tsx
  src/components/MapKakao.tsx
  src/components/Pagination.tsx
  src/components/ReviewItem.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
Labels: fix

#46 apply skeleton ui
  src/pages/Main.tsx
Labels: enhancement
